### ISSUE TITLE
The latest model version is not displayed correctly in documentation

### ISSUE THREAD

**Issue by nutrik** [team-ocean/veros#463]
Hi Dion,

The code block below is not executed correctly during remote documentation generation on the GitHub side. 
However, the locally built documentation looks OK. I was trying to fix it by adding  "-e ." in the ./doc/requirements.txt file to let the remote building system access Veros installation (similar to my local environment), but it did not work.
Could you please take a look at it too?

```
      from veros import __version__ as veros_version
      if "+" in veros_version:
          veros_version, _ = veros_version.split("+")
      print(".. code-block::\n")
      print(f"   $ git clone https://github.com/team-ocean/veros.git -b v{veros_version}")
```

**Comment by dionhaefner** [comment]
It works on the stable docs: https://veros.readthedocs.io/en/stable/introduction/get-started.html

But not on `latest` because the build doesn't refer to a released version, so the version is undefined. I'll add some code that uses `-b main` in that case.

Should we change the default doc version to `stable` (latest release)?

**Comment by nutrik** [comment]
Thanks! 
I do not have opinion about default doc version. I think it works well now.
