### ISSUE TITLE
ENH: more metadata in diagnostic outputs?

### ISSUE THREAD

**Issue by jklymak** [team-ocean/veros#508]
I've been having a great time setting up Veros for a GFD class I'm teaching this fall.  I had two suggestions for metadata in the diagnostics outputs.  Running some parameter space evaluations I found that:

1) it would be nice to have a `settings.comments` that would be a free-form string describing the run, that then is added to the attributes of the netcdf files.

2) it would also seem possible to have an attribute in the diagnostics that is simply the whole setup file, verbatim

Edit: completely appreciate that one should do these things some more robust way - I typically use git - but having the netcdf files be self-documenting could also be helpful

**Comment by dionhaefner** [comment]
Good to hear you are using (and enjoying) Veros!

I agree that outputs should be self-documenting, and I've been thinking about ways to do this. Since the setup file allows for arbitrary code execution, reproducibility is difficult to ensure. Anyhow, a baseline level of reproducibility is probably better than none :)

I like your suggestions, I'll see if I can get that implemented cleanly.

**Comment by dionhaefner** [comment]
Implemented both suggestions. Thanks @jklymak
